spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 测试服
    url: jdbc:mysql://xxx:3306/xxx_rt?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT-7&useSSL=false&allowMultiQueries=true
    username: xxx
    password: xxx
  elasticsearch:
    rest:
      uris: xxx
      username: xxx
      password: xxx
job:
  pre-process: true
